import Location from '../assets/images/map.jpeg'

export default function contactLoader() {
    const frame = document.createElement('div');
    const title = document.createElement('h1');
    const t = document.createElement('div');
    const b = document.createElement('div');
    const tl = document.createElement('div');
    const tr = document.createElement('div');
    const staff = document.createElement('h2');
    const hours = document.createElement('h2');
    const location = document.createElement('h2');
    const p1 = document.createElement('p');
    const p2 = document.createElement('p');
    const p3 = document.createElement('p');
    const p4 = document.createElement('p');
    const p5 = document.createElement('p');
    const p6 = document.createElement('p');
    const p7 = document.createElement('p');
    const p8 = document.createElement('p');
    const p9 = document.createElement('p');
    const p10 = document.createElement('p');
    const p11 = document.createElement('p');
    const txt = ' 8am - 6pm';
    const map = new Image();
    
    map.id = 'map';
    map.src = Location;
    p1.textContent = 'Monday:' + txt;
    p2.textContent = 'Tuesday: 8am - 8pm';
    p3.textContent = 'Wednesday:' + txt;
    p4.textContent = 'Thursday:' + txt;
    p5.textContent = 'Friday:' + txt;
    p6.textContent = 'Saturday:' + txt;
    p7.textContent = 'Sunday: Closed';
    p8.textContent = 'Owner/Founder: Eugene H. Krabs';
    p9.textContent = 'Fry Cook: SpongeBob SquarePants';
    p10.textContent = 'Cashier/Waiter: Squidward Tentacles';
    p11.textContent = 'Bikini Bottom, Pacific Ocean';
    staff.textContent = 'Staff';
    hours.textContent = 'Hours';
    location.textContent = 'Location';
    t.id = 'topContact';
    b.id = 'bottomContact';
    frame.id = 'frame';
    tl.id = 'staff';
    title.textContent = 'Contact Us';
    tl.appendChild(staff);
    tr.appendChild(hours);
    tr.appendChild(p1);
    tr.appendChild(p2);
    tr.appendChild(p3);
    tr.appendChild(p4);
    tr.appendChild(p5);
    tr.appendChild(p6);
    tr.appendChild(p7);
    tl.appendChild(p8);
    tl.appendChild(p9);
    tl.appendChild(p10);
    b.appendChild(location);
    b.appendChild(p11);
    b.appendChild(map);
    t.appendChild(tl);
    t.appendChild(tr);
    frame.appendChild(title);
    frame.appendChild(t);
    frame.appendChild(b);
    return frame;
}
